language: go
go:
- '1.13'
notifications:
  slack:
    secure: V6rc2qmuHFJO28KzcRFzeb4lq+Hexjbj6GhEYZAN8hlipV7ogcsqY7pyWFiYbDSG869YcZ1ct74KeKOY28nb0fZJYoX55SAacUr1noA9cWecQynzjKqKyBUI1alTa7VIOm3AJpmq3UGMSmQMLc4vC48WJPl/+xPhQOHzPrXkd4f8W+i8Y7O2gyUNCQcpj8YxVPtIpvZt9uNH6NmdvGksEIYkdnF2f5hLqrPFMaOOBUZHNI8i4fhzJxapaASxQHnLckb+fN6i24YD5IhBxf7OSTCR1/x5eufvKZbbRuFEH62N9XanzfWcZtR8rw7hf0b43yHknoX1J7YJ8V6O0OqQNl4pOt1Djf2djYOyvVUls6u5GHNlrgxv4ST8PsIaDZlxhbGpFGMmHprNh8ysV3iWaDbw9u/J3jz44/mS3jIfudGNrQrWaqohTseu6cT2xp+PDinvIdJwF6h210eF8P1cgM5qOkHEzdCSv+NC0kdvhJpoO01OXPLnwtto9c4gJ7EvREgzpr3DMGLYmLL6ybeGJo66oBYPM0sCI7tdYSm/MG1DmOnSt/xnpWQGxKnnR+nThFdBosoRd+DLtZ/QuQ11ozOFGhO2nJ2UIq7wiZkGuZdhwXyi9iB7hcYTZXW/yatEVSd165iYND42xlI7m0bY7hvHzfhytxyJ9noYqSv3J7Y=
